#include<iostream>
using namespace std;

// CONTAINERS IN STL
// CONTAINER IS AN OBJECT THAT STORE DATA
// ALGORITM PROCEDURE TO PROCESS LIKE SEARCHING , SORING , INDEXING  DATA
// ITERATOR IS A OBJECT WHICH POINTS TO AN ELEMNET OF A CONTAINER

// ------------------CONTAINER AND IS TYPES---------------->
// TYPE 1 -> SEQUENCE CONTAINERS -----> LINEAR FASHION MEI STORE DATA - O(2)----->O(3)------>O(33)---->O(35)  EXAMPLES VECTORS , LIST , DEQUEUE
// TYPE 2 -> ASSOCIATIVE CONTAINERS --> DIRECT ACCESS  FAST SEARCHING  DELETION AND ADDITION USE LIKE A TREE IT STORES THE DATA  EXAMPLES SET, MULTISET , MAP , MULTIMAP
// TYPE 3 -> DERIVED CONTAINERS ------> REAL WORLD MODELLING EXAMPLES STACK, QUEUE , PRIORITY QUERE 

// ----------------- When to use Which ----------------------- 
// VECTOR - RANDOM ACCESS = FAST AND (INSERTION , DELECTION) IS SLOW IN MIDDLE AND INSERTION AT THE END IS FAST
// LIST - RANDOM ACCESS IS SLOW (INSERTION /DELETION IN MIDDLE IS FAST A COMPARED TO ARRAY)  AND INSERTION / DELETIONAT THE END IS FAST
// ASSOCIATIVE ALL OPERATION FAST EXCEPT RANDOM ACCESS AS IT IS A TREE DATA STRUCTURE AND WILL BE SLOW
// DERIVED CONTAINERS -> DEPENDS --> DATA STRUCTURE
// 

int main(){
   
return 0;
}
